### ISSUE TITLE
Error on /transactions endpoing

### ISSUE THREAD

**Issue by jjmardlin** [emilioTe/node-coinbase-api#5]
Hi thanks again for this great tool. 

Here's my error output.
```                                                                                                                                                        
TypeError: undefined is not a function                                                                                                                  
    at Request.module.exports [as _callback] (/home/ubuntu/workspace/node_modules/coinbase-api/lib/deps/req.js:46:9)                                    
    at Request.init.self.callback (/home/ubuntu/workspace/node_modules/coinbase-api/node_modules/request/request.js:129:22)                             
    at Request.emit (events.js:98:17)                                                                                                                   
    at Request.onResponse (/home/ubuntu/workspace/node_modules/coinbase-api/node_modules/request/request.js:873:14)                                     
    at Request.emit (events.js:117:20)                                                                                                                  
    at IncomingMessage.Request.onResponse.buffer (/home/ubuntu/workspace/node_modules/coinbase-api/node_modules/request/request.js:824:12)              
    at IncomingMessage.emit (events.js:117:20)                                                                                                          
    at _stream_readable.js:943:16                                                                                                                       
    at process._tickCallback (node.js:419:13)                                                                                                           
```
My script: 
```
var coinbase = require("./modules.js").coinbase; 

//this code doesn't work
coinbase.transactions.list(function(err, json) {
    if (err) return console.log(err);
    console.log(json);
});

//this code does
coinbase.accounts.list(function(err, json) {
     if (err) return console.log(err);    
     console.log(json);
 });

```

**Comment by emilioTe** [comment]
Looking into it now..
